name: CI
on: [push, pull_request]
jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, v20.11.1, 22.x, 23.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'package.json'

      - run: npm install
      - run: npm run ci-tests

      - name: Deploy docs
        if: github.ref == 'refs/heads/main' && matrix.node-version == 'v20.11.1'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          single-commit: true
          branch: gh-pages
          folder: typedoc

